services:
  backend:
    image: my-backend-image:latest
    environment:
      - PRODUCTION=${PRODUCTION}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PRODUCTION_DB_URL=${PRODUCTION_DB_URL}
    container_name: my-backend-container
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: custom-nginx:latest
    container_name: my-nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
