services:
  backend:
    image: my-backend-image:latest
    environment:
      - PRODUCTION=${PRODUCTION}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PRODUCTION_DB_URL=${PRODUCTION_DB_URL}
    container_name: my-backend-container
    ports:
      - 80:8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
