version: "3.8"
networks: my-network

services:
  backend:
    image: my-backend-image:latest
    environment:
      - PRODUCTION=${PRODUCTION}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PRODUCTION_DB_URL=${PRODUCTION_DB_URL}
    container_name: my-backend-container
    ports:
      - 8000
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: my-nginx-container
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - my-network
